/* Banco ampliado: usado no quiz do jogador e no Modo Professor. Depende de data.js (QUIZ). */
const QUIZ_CATS=["Phishing e golpes","Engenharia social","Contas, senhas e MFA","Malware e ransomware","Phishing e golpes","Phishing e golpes","Engenharia social","LGPD: conceitos","Contas, senhas e MFA","Incidentes e resposta","Malware e ransomware","Phishing e golpes"];
const NEWQ=[
 {cat:"Phishing e golpes",q:"O que é \"quishing\"?",o:["Phishing que usa QR code","Um vírus que apaga arquivos","Golpe feito só por ligação","Uma senha com 10 dígitos"],a:0,w:"Quishing é phishing por QR code: o código esconde o destino real e leva a vítima ao celular."},
 {cat:"Phishing e golpes",q:"O domínio \"rnicrosoft.example\" (r + n no lugar de m) é um exemplo de…",o:["Criptografia","Domínio parecido (typosquatting) para enganar a leitura","Certificado válido","Atualização oficial"],a:1,w:"Trocas visuais (rn por m, 0 por o) imitam marcas. Leia o domínio letra por letra."},
 {cat:"Engenharia social",q:"Quais gatilhos aparecem em quase todo golpe de engenharia social?",o:["Humor, curiosidade e nostalgia","Urgência, autoridade e medo ou recompensa","Tecnologia, preço e prazo de garantia","Cores, imagens e logotipos"],a:1,w:"Golpistas exploram emoções e atalhos mentais: pressa, obediência a chefes, medo de perder ou ganho fácil."},
 {cat:"Engenharia social",q:"Você recebe um vídeo do CFO pedindo uma transferência urgente. A melhor conduta é…",o:["Transferir, pois você viu e ouviu o CFO","Confirmar por canal conhecido e seguir o processo de aprovação","Pedir que ele envie o pedido por WhatsApp","Transferir metade do valor"],a:1,w:"Vídeo e voz podem ser falsificados por IA (caso Arup). Valide por contato conhecido e pelo fluxo de aprovação."},
 {cat:"Contas, senhas e MFA",q:"Você recebe dezenas de pedidos de aprovação de MFA que não fez (\"MFA fatigue\"). O que fazer?",o:["Aprovar um para parar as notificações","Negar todos, trocar a senha e avisar a TI","Ignorar o celular por uma hora","Desinstalar o aplicativo de MFA"],a:1,w:"O atacante já tem sua senha e insiste até alguém aprovar. Negue, troque a senha e reporte."},
 {cat:"Contas, senhas e MFA",q:"Qual método de MFA costuma resistir melhor a phishing?",o:["Código por SMS","Pergunta secreta","Chave de segurança ou passkey (FIDO2)","Senha mais longa"],a:2,w:"Chaves e passkeys só funcionam no site verdadeiro, então o phishing não consegue reaproveitá-las. SMS pode ser desviado."},
 {cat:"Contas, senhas e MFA",q:"Um gerenciador de senhas ajuda principalmente porque…",o:["Cria e guarda senhas longas e únicas para cada serviço","Deixa todas as contas com a mesma senha","Dispensa o MFA","Evita todos os golpes"],a:0,w:"Senha única por serviço limita o estrago de um vazamento. Use também MFA."},
 {cat:"Malware e ransomware",q:"Muitos ransomwares copiam os dados antes de criptografar e ameaçam publicá-los. Isso é chamado de…",o:["Dupla extorsão","Backup remoto","Autenticação forte","Anonimização"],a:0,w:"Mesmo restaurando o backup, os dados já podem ter vazado. Por isso há também obrigações da LGPD."},
 {cat:"Malware e ransomware",q:"Suspeitou de ransomware no seu computador. A primeira ação é…",o:["Pagar o resgate rapidamente","Isolar da rede e acionar a TI ou a resposta a incidentes","Apagar os arquivos suspeitos","Reiniciar e continuar trabalhando"],a:1,w:"Conter e avisar. Isolar impede a propagação e preservar evidências ajuda a investigação."},
 {cat:"LGPD: conceitos",q:"A biometria usada para identificar uma pessoa é, na LGPD, um dado…",o:["Não pessoal","Pessoal comum","Pessoal sensível","Público e livre"],a:2,w:"Dado biométrico vinculado a uma pessoa natural está entre os dados sensíveis (art. 5º, II)."},
 {cat:"LGPD: conceitos",q:"Na LGPD, quem toma as decisões sobre o tratamento dos dados pessoais é o…",o:["Operador","Titular","Controlador","Encarregado"],a:2,w:"Controlador decide. O operador trata em nome do controlador. O encarregado é o canal de comunicação."},
 {cat:"LGPD: conceitos",q:"Qual é o papel do encarregado (DPO)?",o:["Aplicar multas","Ser o canal entre o controlador, os titulares e a ANPD","Programar os sistemas","Substituir o jurídico"],a:1,w:"O encarregado orienta, recebe solicitações dos titulares e conversa com a ANPD."},
 {cat:"LGPD: conceitos",q:"O princípio da necessidade significa…",o:["Guardar todos os dados possíveis","Limitar o tratamento ao mínimo necessário para a finalidade","Pedir consentimento sempre","Compartilhar com parceiros"],a:1,w:"Coletar e compartilhar só o indispensável reduz risco e impacto de um vazamento (art. 6º)."},
 {cat:"LGPD: obrigações e sanções",q:"A multa simples da LGPD, por infração, pode chegar a…",o:["1% do faturamento, sem teto","2% do faturamento, limitada a R$ 50 milhões","R$ 1 milhão fixo","10% do faturamento"],a:1,w:"Art. 52: até 2% do faturamento no Brasil, limitada a R$ 50 milhões por infração. Há ainda outras sanções."},
 {cat:"LGPD: obrigações e sanções",q:"Em regra, o prazo para comunicar à ANPD e aos titulares um incidente com risco relevante é de…",o:["24 horas corridas","3 dias úteis","30 dias","1 ano"],a:1,w:"A Resolução CD/ANPD nº 15/2024 fixa, em regra, 3 dias úteis a partir da ciência de que o incidente afetou dados pessoais."},
 {cat:"LGPD: obrigações e sanções",q:"Qual destes é um direito do titular de dados?",o:["Receber lucros da empresa","Pedir a correção de dados incompletos ou desatualizados","Escolher o salário do encarregado","Impedir qualquer tratamento de dados"],a:1,w:"Art. 18: confirmação, acesso, correção, anonimização ou eliminação, portabilidade, informação e revogação do consentimento."},
 {cat:"Terceiros e continuidade",q:"Segundo o DBIR 2026 da Verizon, qual a proporção de violações que envolveram terceiros?",o:["8%","19%","48%","92%"],a:2,w:"48% das violações analisadas. Por isso fornecedores precisam de acesso mínimo, prazo e revisão."},
 {cat:"Terceiros e continuidade",q:"O fornecedor terminou o atendimento remoto. A boa prática é…",o:["Deixar o acesso aberto para próximos chamados","Revogar o acesso temporário e registrar a ação","Trocar apenas a senha do notebook","Pedir que ele apague o histórico"],a:1,w:"Acesso de terceiros deve ser temporário, com privilégio mínimo, registrado e revogado ao concluir."},
 {cat:"IA e privacidade",q:"Colar uma planilha de RH com dados de pessoas em um chatbot público é…",o:["Seguro, pois é só um resumo","Arriscado: use ferramenta aprovada e minimize ou anonimize os dados","Obrigatório pela LGPD","Permitido se você apagar depois"],a:1,w:"Dados enviados a serviços externos podem ser retidos ou usados. Exija finalidade, minimização e ferramenta aprovada."},
 {cat:"Casos reais",q:"No caso Arup (2024), o que enganou o funcionário?",o:["Um vírus no computador","Uma videochamada com deepfakes dos executivos","Um e-mail com anexo .exe","Um QR code no refeitório"],a:1,w:"Os sistemas não foram invadidos: as pessoas foram enganadas por imitações de IA. Perda de cerca de US$ 25 milhões."},
 {cat:"Casos reais",q:"No incidente do Defesa Civil Alerta (jun/2026), o problema ocorreu…",o:["Nos celulares de quem recebeu","Na plataforma de envio, que foi invadida","Na rede elétrica","Nos aplicativos de banco"],a:1,w:"Receber o alerta não significa que o celular foi invadido. A entrada foi na plataforma de envio, investigada pela PF."},
 {cat:"Casos reais",q:"O pagamento de US$ 11 milhões da JBS, em 2021, representa…",o:["O custo total do incidente","O valor do resgate divulgado, não o custo total","Uma multa da LGPD","O lucro anual da empresa"],a:1,w:"É só o pagamento divulgado. Ainda houve turnos cancelados e custos de recuperação."},
 {cat:"Casos reais",q:"No assalto ao Louvre (out/2025), como os ladrões chegaram às joias?",o:["Invadiram o sistema de câmeras pela internet","Usaram um elevador de carga com escada e cortaram uma janela da Galeria de Apolo","Clonaram o crachá de um funcionário","Hackearam o alarme com um aplicativo"],a:1,w:"Foi um ataque físico, em poucos minutos, por uma área em obras. Não há registro de invasão digital no assalto. A parte digital do caso são as falhas antigas que vieram à tona depois."},
 {cat:"Casos reais",q:"Segundo reportagem do Libération sobre uma auditoria da ANSSI de 2014, qual era a senha do sistema de vigilância por vídeo do Louvre?",o:["Louvre2014!","LOUVRE","Mona-Lisa-Paris","admin123"],a:1,w:"A senha era o próprio nome do museu. O mesmo relatório diz que os auditores conseguiram manipular câmeras e acessos por crachá. Senha previsível é o primeiro item de qualquer auditoria."},
 {cat:"Casos reais",q:"Qual lição de segurança digital o caso do Louvre ilustra?",o:["Só ataques digitais sofisticados derrubam grandes organizações","Falhas já apontadas em auditorias (senha trivial, sistemas sem suporte) precisam ser corrigidas, e segurança física e digital andam juntas","Câmeras mais caras resolvem o problema","Senha só importa em sistemas de TI"],a:1,w:"Relatórios apontaram por anos senhas triviais e sistemas obsoletos. Conhecer o risco e não agir tem custo. Controle físico e digital se complementam."}
];
const LIVEQ=QUIZ.map((q,i)=>Object.assign({cat:QUIZ_CATS[i]},q)).concat(NEWQ);
const CATS=[...new Set(LIVEQ.map(q=>q.cat))];
